# q-TIP4P/f water example: MPI (with shared-memory fallback), batching, and
# dipole 'extras'.
#
# This file is part of i-PI.
# i-PI Copyright (C) 2014-2015 i-PI developers
# See the "licenses" directory for full license information.

.PHONY: all clean
all:
	bash run.sh

clean:
	rm -f *simulation.* RESTART EXIT
