# Makefile for the "direct" harmonic oscillator example
#
# This file is part of i-PI.
# i-PI Copyright (C) 2014-2015 i-PI developers
# See the "licenses" directory for full license information.

.PHONY: all clean harmonic
all: harmonic

IPI:=i-pi


harmonic:
	$(IPI) input.xml 

clean:
	rm -f *simulation.* RESTART EXIT
