name: Documentation

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    # Check all PR

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          pip install --upgrade pip
          pip install -r docs/requirements.txt

          sudo apt-get update
          sudo apt-get install -y texlive-latex-extra texlive-lang-greek latexmk
      - name: build documentation
        run: |
          cd docs
          make html
          make latexpdf

          cp _build/latex/i-pi.pdf _build/html/ipi-manual.pdf
      - name: deploy to gh-pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html/
          force_orphan: true
          cname: docs.ipi-code.org
